# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in feature_flag_client.gemspec
gemspec

gem 'rubocop', '~> 0.91.0'

gem 'webmock', '~> 3.9'
