source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in feature-flag-client.gemspec
gemspec

gem "httparty", "~> 0.17.3"

gem "mini_cache", "~> 1.1"
